### ISSUE TITLE
Interesting libraries

### ISSUE THREAD

**Issue by arnolanglade** [nidup/architool#9]
* http://pipeline.thephpleague.com

**FileStorage:**
* https://symfony.com/doc/current/components/filesystem.html
* http://flysystem.thephpleague.com/

**File:**
* http://php.net/manual/fr/spl.files.php
* https://github.com/hoaproject/File
* https://symfony.com/doc/current/components/finder.html

**CommandBus:**
* http://tactician.thephpleague.com/
* http://docs.simplebus.io/en/latest/

**Code generation:**
* https://github.com/Ocramius/CodeGenerationUtils
* https://github.com/memio/memio

**Reflection:**
* https://github.com/Roave/BetterReflection

**Comment by gplanchat** [comment]
My 2 cents

**Code Generation**

https://github.com/nikic/php-ast
